const dishList = [
  {
    dish:"中華飯",
    material1: "白菜",
    material2: "ニンジン",
    material3: "玉ねぎ",
    material4: "うずらの卵",
    material5: "ホウレンソウ",
    material6: "豚バラ",
  },
  {
    dish:"高野豆腐の旨煮",
    material1: "豚ひき肉",
    material2: "ニンジン",
    material3: "玉ねぎ",
    material4: "インゲン",
    material5: "高野豆腐",
    material6: "鶏卵",
  },
  {
    dish:"鮭のちゃんちゃん焼き",
    material1: "鮭",
    material2: "ニンジン",
    material3: "玉ねぎ",
    material4: "キャベツ",
    material5: "小口ネギ",
    material6: "",
  },
  {
    dish:"ドライカレー",
    material1: "牛豚合挽肉",
    material2: "ニンジン",
    material3: "玉ねぎ",
    material4: "ブロッコリー",
    material5: "生姜",
    material6: "ホウレンソウ",
  },
  {
    dish:"明太ビーフン",
    material1: "明太子",
    material2: "もやし",
    material3: "キャベツ",
    material4: "小口ネギ",
    material5: "ビーフン",
    material6: "",
  },
  {
    dish:"ビビンバ",
    material1: "豚ひき肉",
    material2: "もやし",
    material3: "ニンジン",
    material4: "キムチ",
    material5: "ホウレンソウ",
    material6: "鶏卵",
  },
  {
    dish:"ロールキャベツ",
    material1: "牛豚合挽肉",
    material2: "玉ねぎ",
    material3: "キャベツ",
    material4: "トマト缶",
    material5: "ホウレンソウ",
    material6: "鶏卵",
  },  
  {
    dish:"チキン南蛮",
    material1: "鶏ムネ",
    material2: "玉ねぎ",
    material3: "鶏卵",
    material4: "",
    material5: "",
    material6: "",
  },  
  {
    dish:"アジの甘酢あんかけ",
    material1: "アジ",
    material2: "玉ねぎ",
    material3: "ニンジン",
    material4: "ピーマン",
    material5: "小口ネギ",
    material6: "",
  },  
  {
    dish:"酢鶏",
    material1: "鶏モモ",
    material2: "玉ねぎ",
    material3: "ニンジン",
    material4: "ピーマン",
    material5: "",
    material6: "",
  },  
  {
    dish:"グラタン",
    material1: "鶏モモ",
    material2: "玉ねぎ",
    material3: "ニンジン",
    material4: "ホウレンソウ",
    material5: "",
    material6: "",
  },  
  {
    dish:"豆乳具沢山スープ",
    material1: "豚ひき肉",
    material2: "玉ねぎ",
    material3: "ニンジン",
    material4: "小口ネギ",
    material5: "キャベツ",
    material6: "",
  },  
  {
    dish:"親子丼",
    material1: "鶏モモ",
    material2: "玉ねぎ",
    material3: "鶏卵",
    material4: "",
    material5: "",
    material6: "",
  }
];

